name: Lint
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.3
      - uses: actions/checkout@v1
      - name: Test
        run: gofmt -d -s -e -l .
